### PR TITLE
Use render function

### PR DESCRIPTION
**Pull request by dotneet**
to use this component in nuxt.js I need to replace the template property with render function.

### CODE REVIEW

**Comment by dotneet** [comment]
I've just found the root cause of this problem now.

A template property requires the vue template compilers.
So when we use vue2-ace-editor  with dynamic import, an exception is happend at runtime.

**Comment by chairuosen** [comment]
So, require a full size vue instead of runtime vue can solve this issue?

**Comment by dotneet** [comment]
Including vue-template-compiler in runtime environment solve this issue.
If this PR is merged, vue2-ace-editor will not require vue-template-compiler at runtime.

**Comment by chairuosen** [comment]
https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only
As it said, *.vue file should pre-compiled by vue-loader an then it can load by runtime-only build of Vue which is default build when you require.
Or, you shouldn't use runtime-only build.

So I think it is not necessary to merge.

But Im still a little curious about how you import my lib dynamically.

**Comment by chairuosen** [comment]
Oh. I guess you don't use vue-loader to load your app. and we usually use it so we didn't find this issue.

I'll add a notice in readme.

**Comment by chairuosen** [comment]
I think you are right. I'll merge it. Thank you :)

**Comment by dotneet** [comment]
@chairuosen Thank you for merging!

**Pull request merged**
